// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsfpufivusrsriqnprby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZnB1Zml2dXNyc3JpcW5wcmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NjI4NzAsImV4cCI6MjA4NzEzODg3MH0.7dnv_TNXJfso5QpRLaS_wHxbX9tIqynNhfX_-fiMzX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});